name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:       # Allows manual runs from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Streamlit app
        run: curl https://rmspricedb.streamlit.app/
